resources:
  - name: docker_repo
    type: GitRepo
    configuration:
      gitProvider: gitIntegration
      path: dmitry-lyutenko/toolbox-images
      branches:
        include: ci-test
  - name: toolbox-image
    type: Image
    configuration:
      registry: gitIntegration
      sourceRepository: toolbox-docker
      imageName: dimoff.jfrog.io/toolbox-docker/toolbox
      imageTag: latest
      autoPull: true
  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: gitIntegration
      buildName: docker_build
      buildNumber: 1
  - name: docker_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: gitIntegration
      buildName: docker_build
      buildNumber: 1
pipelines:  
  - name: basic_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"  
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: grDocker
          dockerFileLocation: .
          dockerImageName: dimoff.jfrog.io/toolbox-docker/toolbox
          dockerImageTag: ${run_number}
          inputResources:
            - name: docker_repo
          integrations:
            - name: gitIntegration
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: grDocker
          targetRepository: toolbox-docker
          integrations:
            - name: gitIntegration
          inputSteps:
            - name: docker_build
          outputResouces:
            - name: docker_image
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResouces:
            - name: docker_build_info
      - name: promote_build
        type: PromoteBuild
        configuration:
          targetRepository: toolbox-docker
          integrations:
            - name: gitIntegration
          inputResources:
            - name: docker_build_info
          outputResouces:
            - name: docker_promoted_build_info
