name: Docker Image CI

on:
  push:
    branches: [ "ci-test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: env
        #  docker build . --file Dockerfile --tag toolbox:v0.0.1

      - name: Login to docker hub
        run: echo $DOCKER_HUB_AUTH | tee ~/.docker/config.json 

      - name: Relabel (version)
        run: docker tag toolbox:v0.0.1 egiptyanin/toolbox:v0.0.1

      - name: Relabel (latest)
        run: docker tag toolbox:v0.0.1 egiptyanin/toolbox:latest

      - name: Publish
        run: docker push egiptyanin/toolbox:latest

      - name: Logout
        run: docker logout && echo "trash" > ~/.docker/config.json && rm -f ~/.docker/config.json
