name: Docker Image CI

on:
  push:
    branches: [ "ci-test" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag toolbox:$GITHUB_SHA

  push:
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Relabel (version)
        run: docker tag toolbox:$GITHUB_SHA egiptyanin/toolbox:$GITHUB_REF

      - name: Relabel (latest)
        run: docker tag toolbox:$GITHUB_SHA egiptyanin/toolbox:latest

      - name: Publish
        run: docker push egiptyanin/toolbox:latest

      - name: Publish ()
        run: docker image ls

      - name: Logout
        run: docker logout && echo "trash" > ~/.docker/config.json && rm -f ~/.docker/config.json
